[build-system]
requires = ["setuptools>=80.9.0", "wheel", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name = "pIMOS"
dynamic = ["version"]
dependencies = [
    "numpy==1.24.2",
    "scipy",
    "matplotlib",
    "xarray",
    "pandas",
    "dolfyn==1.2.0",
    "turbo_lance",
]

[tool.setuptools_scm]
version_file = "pIMOS/_version.py"